//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Defaults"",
            ""id"": ""5bce3dcc-13bb-4997-a08e-36ecf2b9ac0c"",
            ""actions"": [
                {
                    ""name"": ""Cut"",
                    ""type"": ""Value"",
                    ""id"": ""5de7f9af-e11c-4746-baf7-58ec64d67511"",
                    ""expectedControlType"": ""Touch"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2757a6c6-f05e-4ffc-9a1e-703dbef30489"",
                    ""path"": ""<Touchscreen>/primaryTouch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Defaults
        m_Defaults = asset.FindActionMap("Defaults", throwIfNotFound: true);
        m_Defaults_Cut = m_Defaults.FindAction("Cut", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Defaults
    private readonly InputActionMap m_Defaults;
    private List<IDefaultsActions> m_DefaultsActionsCallbackInterfaces = new List<IDefaultsActions>();
    private readonly InputAction m_Defaults_Cut;
    public struct DefaultsActions
    {
        private @Controls m_Wrapper;
        public DefaultsActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Cut => m_Wrapper.m_Defaults_Cut;
        public InputActionMap Get() { return m_Wrapper.m_Defaults; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultsActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultsActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultsActionsCallbackInterfaces.Add(instance);
            @Cut.started += instance.OnCut;
            @Cut.performed += instance.OnCut;
            @Cut.canceled += instance.OnCut;
        }

        private void UnregisterCallbacks(IDefaultsActions instance)
        {
            @Cut.started -= instance.OnCut;
            @Cut.performed -= instance.OnCut;
            @Cut.canceled -= instance.OnCut;
        }

        public void RemoveCallbacks(IDefaultsActions instance)
        {
            if (m_Wrapper.m_DefaultsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultsActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultsActions @Defaults => new DefaultsActions(this);
    public interface IDefaultsActions
    {
        void OnCut(InputAction.CallbackContext context);
    }
}
